version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: quesSystemMysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=quesSystem
      - MYSQL_USER=quesSystem
      - MYSQL_PASSWORD=quesSystem123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - "./configs/mysql/data/:/var/lib/mysql"