# Generated by Django 4.2.5 on 2023-09-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question_id',
            new_name='project_id',
        ),
    ]
