# Generated by Django 4.2.5 on 2023-09-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_question_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
