# Generated by Django 4.2.5 on 2023-09-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_project_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'project2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('answer', models.JSONField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project2')),
            ],
            options={
                'db_table': 'survey_responses',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
