# Generated by Django 4.2.5 on 2023-09-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_project2_project_alter_project_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponses',
            old_name='project_id',
            new_name='project',
        ),
    ]
