# Generated by Django 4.2.5 on 2023-10-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
