# Generated by Django 4.2.5 on 2023-10-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_user_options_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
